apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: angousa/laravel-app
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: angousa-data.db
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: Hello@123
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: laravel
